In [1]:
# 1 Create a NumPy array 'arr' of integers from 0 to 5 and print its data type. 
import numpy as np
import random
arr = np.arange(0,6)

In [2]:
arr

array([0, 1, 2, 3, 4, 5])

In [3]:
arr.dtype

dtype('int32')

In [4]:
#2 Given a NumPy array 'arr', check if its data type is float64. 
arr = np.array([1.5, 2.6, 3.7])
arr.dtype

dtype('float64')

In [5]:
#3 Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
complex_no = np.array([3+2j,5+7j,1+4j]) # complex no is x+yj.

In [6]:
complex_no.dtype

dtype('complex128')

In [7]:
#4 Convert an existing NumPy array 'arr' of integers to float32 data type.
inte = np.array([1,2,3,4,5])

In [8]:
inte

array([1, 2, 3, 4, 5])

In [9]:
inte.dtype

dtype('int32')

In [10]:
inte = np.float32(inte)

In [11]:
inte

array([1., 2., 3., 4., 5.], dtype=float32)

In [12]:
# 5 Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
flo = np.array([1.1,2.1,3.1,4.1])
flo.dtype

dtype('float64')

In [13]:
flo = np.float32(flo)
flo

array([1.1, 2.1, 3.1, 4.1], dtype=float32)

In [14]:
# 6 Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
def array_attributes(a):
    print("the shape of given array is : ",a.shape)
    print("the size of given array is : ",a.size)
    print("the data type of given array is : ",a.dtype)
    return a

In [15]:
array_attributes(np.array([[8,5,4],[2,7,11]]))

the shape of given array is :  (2, 3)
the size of given array is :  6
the data type of given array is :  int32


array([[ 8,  5,  4],
       [ 2,  7, 11]])

In [16]:
# 7 Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
def array_dimension(a):
     print("the dimension of given array is : ",a.ndim)   
     return a   

In [17]:
array_dimension(np.random.randint(1,5,(1,2,3)))

the dimension of given array is :  3


array([[[4, 4, 2],
        [1, 1, 4]]])

In [18]:
# 8 Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.
def item_size_info(a):
    print("the item size of given array is : ",a.size)
    print("the data type of given array is : ",a.dtype)
    print("the total bytes of given array is : ",a.nbytes) 
    return a

In [19]:
item_size_info(np.random.rand(5,3)) # array of 64-bit float(each 8 bytes)

the item size of given array is :  15
the data type of given array is :  float64
the total bytes of given array is :  120


array([[0.68756869, 0.86930532, 0.28220483],
       [0.14059456, 0.99792444, 0.11427046],
       [0.95632871, 0.13493068, 0.01661797],
       [0.17569945, 0.10424927, 0.56211662],
       [0.38274086, 0.61539213, 0.82905665]])

In [20]:
item_size_info(np.random.randint(1,10,(5,3))) # array of 32-bit intergers(each 4 bytes)

the item size of given array is :  15
the data type of given array is :  int32
the total bytes of given array is :  60


array([[9, 1, 6],
       [2, 2, 5],
       [4, 1, 8],
       [1, 5, 8],
       [7, 1, 2]])

In [21]:
# 9 Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
def array_strides(a):
    print("the data type of given array is : ",a.dtype)
    print("the strides of given array is : ",a.strides)
    return a

In [22]:
array_strides(np.random.randint(1,10,(2,6)))
# array of 32-bit integers (each 4 bytes)
#this array is stored in memory as 48 (4 bytes * 12 element) bytes, one after the other  (known as a contiguous block of memory). 
#The strides of an array tell us how many bytes we have to skip in memory to move to the next position along a certain axis. 
#For example, we have to skip 4 bytes (1 value) to move to the next column, but 24 bytes (6 values) to get to the same position in the next row. 
#As such, the strides for the array a will be (24, 4).

the data type of given array is :  int32
the strides of given array is :  (24, 4)


array([[4, 9, 3, 9, 3, 8],
       [9, 8, 2, 3, 3, 2]])

In [23]:
# 10 Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
def shape_stride_relationship(a):
    print("the shape of given array is : ",a.shape)
    print("the data type of given array is : ",a.dtype)
    print("the strides of given array is : ",a.strides)
    return a

In [24]:
shape_stride_relationship(np.random.rand(2,4))
# array of 64-bit float (each 8 bytes)
#this array is stored in memory as 64 (8 bytes * 8 element) bytes, one after the other  (known as a contiguous block of memory). 
#The strides of an array tell us how many bytes we have to skip in memory to move to the next position along a certain axis. 
#For example, we have to skip 8 bytes (1 value) to move to the next column, but 32 bytes (4 values) to get to the same position in the next row. 
#As such, the strides for the array a will be (24, 4).

the shape of given array is :  (2, 4)
the data type of given array is :  float64
the strides of given array is :  (32, 8)


array([[0.88623069, 0.49216408, 0.86253759, 0.83516573],
       [0.60225979, 0.04025681, 0.96256858, 0.79174413]])

In [25]:
# 11 Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.
def create_zeros_array(n):
    return np.zeros(n)

In [26]:
create_zeros_array(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [27]:
# 12 Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs 
# and generates a 2D NumPy array filled with ones of size `rows x cols`.
def create_ones_matrix(n):
    return np.ones(n) 

In [28]:
create_ones_matrix((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
# 13 Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting 
# from `start`, ending at stop (exclusive), and with the specified `step`.
def generate_range_array(start,stop,step):
    return np.arange(start,stop,step)

In [30]:
generate_range_array(1,11,3)

array([ 1,  4,  7, 10])

In [31]:
# 14 Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with 
# num equally spaced values between `start` and `stop` (inclusive).
def generate_linear_space(start,stop,num):
    return np.linspace(start,stop,num)

In [32]:
generate_linear_space(0.5,5.5,10)

array([0.5       , 1.05555556, 1.61111111, 2.16666667, 2.72222222,
       3.27777778, 3.83333333, 4.38888889, 4.94444444, 5.5       ])

In [33]:
# 15 Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `nxn` using `numpy.eye`.
def create_identity_matrix(n):
    return np.eye(n)

In [34]:
create_identity_matrix(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
# 16 Write a function that takes a Python list and converts it into a NumPy array.
def list_to_array(a):
    return np.asarray(a) # asanyarray(a) will also gave same result,diffrence is asarray() convert both non-array and array into array but asanyarray() convert only non-array into aaray.

In [36]:
list_to_array([5,8,4,3,7,9,11])

array([ 5,  8,  4,  3,  7,  9, 11])

In [37]:
# 17  Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [38]:
view_arr1 = arr1.view()

In [39]:
view_arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
view_arr1[0,0] = 47

In [41]:
view_arr1

array([[47,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [42]:
arr1

array([[47,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [43]:
# 18 Write a function that takes two NumPy arrays and concatenates them along a specified axis.
def concatenate_array(arr1,arr2,axis):
    if arr1.shape[axis] != arr2.shape[axis]:
        raise
    ValueError(f"Array cannot be concatenated along axis {axis} because their dimensions do not match.")
    return np.concatenate((arr1,arr2),axis=axis)

In [44]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

In [45]:
concatenate_array(arr1,arr2,axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
concatenate_array(arr1,arr2,axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [47]:
# 19 Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8],[9,10]])

In [48]:
con_arr = np.concatenate((arr1,arr2),axis=1)

In [49]:
con_arr

array([[ 1,  2,  3,  7,  8],
       [ 4,  5,  6,  9, 10]])

In [50]:
# 20 Write a function that vertically stacks multiple NumPy arrays given as a list.
def vertical_stack(arrays_list):
    return np.vstack(arrays_list)

In [51]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
arr3 = np.array([[13,14,15]])
arr4 = np.array([[16,17,18]])
arrays_list = [arr1,arr2,arr3,arr4]

In [52]:
vertical_stack(arrays_list)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [53]:
# 21  Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
def integer_array(start,stop,step):
    return np.arange(start,stop+1,step)

In [54]:
integer_array(1,11,2)

array([ 1,  3,  5,  7,  9, 11])

In [55]:
# 22 Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
def equally_spaced_array(start,stop,num):
    return np.linspace(start,stop,num)

In [56]:
equally_spaced_array(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [57]:
# 23 Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
def log_spaced(start,stop,num):
    start_log = np.log10(start) # Convert start and stop to their logarithmic values
    stop_log = np.log10(stop)
    return np.logspace(start_log,stop_log,num)

In [58]:
log_spaced(1,1000,5)

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

In [59]:
# 24 Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
import pandas as pd
arr = np.random.randint(1,100,(5,3))

In [60]:
arr

array([[ 6, 64, 79],
       [34, 57, 91],
       [25, 20, 15],
       [62, 80, 14],
       [40, 33, 25]])

In [61]:
df= pd.DataFrame(arr)
df.columns = ['column 1','column 2','column 3']

In [62]:
df

column 1  column 2  column 3
0         6        64        79
1        34        57        91
2        25        20        15
3        62        80        14
4        40        33        25

In [63]:
# 25 Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros.
# Use NumPy operations within the Pandas DataFrame.
def replace_negative_with_zero(df, column_name,column_name_2):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    df[column_name_2] = np.where(df[column_name_2] < 0, 0, df[column_name_2])
    return df

In [64]:
data = {'col_1': [28, -39, 19, -4, 52],'col_2': [-11, 8, 12, -21, 17]}
df = pd.DataFrame(data)

In [65]:
df

col_1  col_2
0     28    -11
1    -39      8
2     19     12
3     -4    -21
4     52     17

In [66]:
replace_negative_with_zero(df,'col_1','col_2')

col_1  col_2
0     28      0
1      0      8
2     19     12
3      0      0
4     52     17

In [67]:
# 26 Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])

In [68]:
arr[2]

30

In [69]:
# 27 Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [70]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
arr_2d[1,2]

6

In [72]:
# 28 Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])

In [73]:
arr[arr>5]

array([ 8, 10,  7])

In [74]:
#29 Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
arr[2:6]

array([3, 4, 5, 6])

In [76]:
# 30 Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [77]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
arr_2d[0:2,[1,2]]

array([[2, 3],
       [5, 6]])

In [79]:
# 31 Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
def extract_elenemts(arr_2d,indices):
   rows,cols = indices[:,0],indices[:,1]
   return arr_2d[rows,cols]

In [80]:
arr_2d = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
indices = np.array([[0,1],[1,2],[2,0]])

In [81]:
extract_elenemts(arr_2d,indices)

array([20, 60, 70])

In [82]:
# 32 Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
import numpy as np
import random
def filter_element(arr,threshold):
    print("array is: \n",arr)
    return arr[arr>threshold]

In [83]:
filter_element(np.random.randint(1,11,(3,7)),5)

array is: 
 [[ 5  1  2  7 10  7  9]
 [ 8 10  7  7  6  7  8]
 [ 4  9  5  1  9  9  9]]


array([ 7, 10,  7,  9,  8, 10,  7,  7,  6,  7,  8,  9,  9,  9,  9])

In [84]:
# 33 Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
def extract_elenemts_3d(arr_3d,x_indices,y_indices,z_indices):
    x_indices = np.asarray(x_indices)
    y_indices = np.asarray(y_indices)
    z_indices = np.asarray(z_indices)
    if (len(x_indices)) != (len(y_indices)) != (len(z_indices)):
        print("lenght is not equal for all araay")
    return arr_3d[x_indices,y_indices,z_indices]

In [85]:
arr_3d = np.random.randint(1,15,(3,3,3))

In [86]:
arr_3d

array([[[ 2,  3, 14],
        [ 4,  2,  9],
        [ 7,  8,  9]],

       [[ 7,  2,  7],
        [14,  8,  5],
        [12,  5,  4]],

       [[13, 13,  4],
        [12,  4,  2],
        [ 1,  4,  1]]])

In [87]:
x_indices = np.array([0,1,2])
y_indices = np.array([1,2,2])
z_indices = np.array([2,2,1])

In [88]:
extract_elenemts_3d(arr_3d,x_indices,y_indices,z_indices)

array([9, 4, 4])

In [89]:
# 34 Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
arr = np.random.randint(1,30,(3,7))
def and_condition(arr,con1,con2):
    print("array is: \n",arr)
    print("filtered array is:",arr[(arr>con1) & (arr<con2)])

In [90]:
and_condition(arr,10,25)

array is: 
 [[ 3 10 26  9 20 22 25]
 [20 22 28  9  8  1  1]
 [24  8 16  6 11 20  8]]
filtered array is: [20 22 20 22 24 16 11 20]


In [91]:
# 35 Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
def extract_elenemts(ar_2d,row_indices,col_indices):
    row_indices = np.array(row_indices)
    col_indices = np.array(col_indices)
    return arr[row_indices,col_indices]

In [92]:
ar_2d = np.array([[1,2,3,4],[5,6,7,8],[8,9,10,11]])
row_indices = np.array([0,1,2])
col_indices = np.array([0,1,2])

In [93]:
extract_elenemts(ar_2d,row_indices,col_indices)

array([ 3, 22, 16])

In [94]:
# 36 Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
arr = np.random.randint(4,9,(3,3))

In [95]:
arr

array([[7, 8, 6],
       [8, 4, 5],
       [6, 8, 8]])

In [96]:
arr + 5

array([[12, 13, 11],
       [13,  9, 10],
       [11, 13, 13]])

In [97]:
# 37 Consider two arrays arr1 of shape (3, 1) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 
# using NumPy broadcasting.
arr1 = np.random.randint(1,6,(3,1))
arr2 = np.random.randint(5,10,(3,4))

In [98]:
arr1

array([[5],
       [5],
       [1]])

In [99]:
arr2

array([[9, 6, 7, 5],
       [5, 6, 9, 6],
       [8, 6, 7, 5]])

In [100]:
arr1 * arr2

array([[45, 30, 35, 25],
       [25, 30, 45, 30],
       [ 8,  6,  7,  5]])

In [101]:
# 38 Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
arr1 = np.random.randint(7,11,(4))
arr2 = np.random.randint(11,16,(3,4))

In [102]:
arr1

array([10, 10,  8, 10])

In [103]:
arr2

array([[13, 15, 14, 15],
       [12, 13, 14, 11],
       [15, 14, 14, 15]])

In [104]:
arr1 + arr2

array([[23, 25, 22, 25],
       [22, 23, 22, 21],
       [25, 24, 22, 25]])

In [105]:
# 39 Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
arr1 = np.random.randint(15,26,(3,1))
arr2 = np.random.randint(26,36,(1,3))

In [106]:
arr1

array([[24],
       [25],
       [18]])

In [107]:
arr2

array([[31, 34, 35]])

In [108]:
arr1 + arr2

array([[55, 58, 59],
       [56, 59, 60],
       [49, 52, 53]])

In [109]:
# 40 Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.
arr1 = np.random.randint(1,6,(3,1,2))
arr2 = np.random.randint(6,11,(1,2,2))

In [110]:
arr1

array([[[2, 5]],

       [[2, 3]],

       [[4, 2]]])

In [111]:
arr2

array([[[ 9, 10],
        [ 9,  8]]])

In [112]:
arr1 * arr2

array([[[18, 50],
        [18, 40]],

       [[18, 30],
        [18, 24]],

       [[36, 20],
        [36, 16]]])

In [113]:
# 41 Calculate column-wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
np.mean(arr[0:2,[0]])

2.5

In [115]:
np.mean(arr[0:2,[1]])

3.5

In [116]:
np.mean(arr[0:2,[2]])

4.5

In [117]:
# 42 Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
np.max(arr[0])

3

In [119]:
np.max(arr[1])

6

In [120]:
# 43 For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
np.max(arr[0:2,[0]])

4

In [122]:
np.max(arr[0:2,[1]])

5

In [123]:
np.max(arr[0:2,[2]])

6

In [124]:
# 45 In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6],[3,5,7]])
def check_even_col(arr):
    even = arr % 2 == 0
    return even.all(axis=0)

In [125]:
check_even_col(arr)

array([False, False, False])

In [126]:
# 46 Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = np.reshape(original_array,(2,3))

In [127]:
reshaped_array

array([[1, 2, 3],
       [4, 5, 6]])

In [128]:
# 47 Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flatten_matrix = input_matrix.flatten() #flatten convert any dimension array into 1-d array.

In [129]:
input_matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [130]:
flatten_matrix

array([1, 2, 3, 4, 5, 6])

In [131]:
# 48 Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

In [132]:
array1

array([[1, 2],
       [3, 4]])

In [133]:
array2

array([[5, 6],
       [7, 8]])

In [134]:
def add_array(arr1,arr2,axis):
    return np.concatenate((arr1,arr2),axis=axis)

In [135]:
add_array(array1,array2,0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [136]:
add_array(array1,array2,1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [137]:
# 49 Create a function that splits an array into multiple sub-arrays along a specified axis.
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
original_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
def split_array(arr1,indices,axis):
    return np.split(arr1,indices,axis=axis)

In [139]:
split_array(original_array,3,0) # 0(row level) , divide into 3 equal part at row level.

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [140]:
split_array(original_array,3,1) # 1(column level) , divide into 3 equal part at column level.

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [141]:
# 50 Write a function that inserts and then deletes elements from a given array at specified indices.
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

In [142]:
def modify_array(original_array,indices_to_insert,values_to_insert,indices_to_delete):
    indices_to_insert = np.array(indices_to_insert)
    values_to_insert = np.array(values_to_insert)
    indices_to_delete = np.array(indices_to_delete)
    modified_array = np.insert(original_array,indices_to_insert,values_to_insert)
    indices_to_delete = np.array([idx for idx in indices_to_delete if idx<len(modified_array)])
    modified_array = np.delete(modified_array,indices_to_delete)
    return modified_array

In [143]:
modify_array(original_array,indices_to_insert,values_to_insert,indices_to_delete)

array([ 1, 10,  4, 11,  5])

In [144]:
# 51 Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
# Perform element-wise addition between `arr1` and `arr2`.
arr1 = np.random.randint(1,10,(10))
arr2 = np.arange(1,11)

In [145]:
arr1

array([1, 1, 2, 8, 2, 5, 4, 5, 7, 4])

In [146]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [147]:
arr1 + arr2

array([ 2,  3,  5, 12,  7, 11, 11, 13, 16, 14])

In [148]:
# 52 Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. 
# Subtract `arr2` from `arr1` element-wise.
arr1 = np.arange(10,0,-1)
arr2 = np.arange(1,11)

In [149]:
arr1

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [150]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [151]:
arr2 - arr1

array([-9, -7, -5, -3, -1,  1,  3,  5,  7,  9])

In [152]:
# 53 Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. 
# Perform element-wise multiplication between `arr1` and `arr2`.
arr1 = np.random.randint(1,6,(5))
arr2 = np.arange(1,6)

In [153]:
arr1

array([5, 1, 4, 3, 4])

In [154]:
arr2

array([1, 2, 3, 4, 5])

In [155]:
arr1 * arr2

array([ 5,  2, 12, 12, 20])

In [156]:
# 54 Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. 
#Perform element-wise division of `arr1` by `arr2`.
arr1 = np.arange(2,11,2)
arr2 = np.arange(1,6)

In [157]:
arr1

array([ 2,  4,  6,  8, 10])

In [158]:
arr2

array([1, 2, 3, 4, 5])

In [159]:
arr1 / arr2

array([2., 2., 2., 2., 2.])

In [160]:
# 55 Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. 
# Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
arr1 = np.arange(1,6)
arr2 = np.arange(5,0,-1)

In [161]:
arr1

array([1, 2, 3, 4, 5])

In [162]:
arr2

array([5, 4, 3, 2, 1])

In [163]:
np.power(arr1,arr2)

array([ 1, 16, 27, 16,  5])

In [164]:
# 56 Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [165]:
sub = "hello"
def count_substring_occurrences(array, substring):
    total_count = 0
    for string in array:
        total_count += string.count(substring)
    return total_count

In [166]:
count_substring_occurrences(arr, sub)

3

In [167]:
# 57 Write a function that extracts uppercase characters from a NumPy array of strings.
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
def extract_upper(arr):
    upper_char =[char for string in arr for char in string if char.isupper()]
    return upper_char 

In [168]:
extract_upper(arr)

['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']

In [169]:
# 58  Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'grape'
new_substring = 'mango'
def replace_substring(arr,old_substring,new_substring):
    modified_array = ([string.replace(old_substring,new_substring) for string in arr])
    return modified_array

In [170]:
replace_substring(arr,old_substring,new_substring)

['apple', 'banana', 'mango', 'pineapple']

In [171]:
arr = np.array(['grape','apple', 'banana', 'grape', 'pineapple','grape'])
old_substring = 'grape'
new_substring = 'mango'
replace_substring(arr,old_substring,new_substring)

['mango', 'apple', 'banana', 'mango', 'pineapple', 'mango']

In [172]:
# 59 Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
def concat_elementwise(arr1,arr2):
    if arr1.shape != arr2.shape:
        print("both array must have the same shaoe")
    concat_arr = np.char.add(arr1,arr2)
    return concat_arr

In [173]:
concat_elementwise(arr1,arr2)

array(['HelloOpen', 'WorldAI'], dtype='<U9')

In [174]:
# 60  Write a function that finds the length of the longest string in a NumPy array.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
def max_lenght(arr):
    char_len = []
    for string in arr:
        lenght = len(string)
        char_len.append(lenght)
    max = np.max(char_len)
    return max

In [175]:
max_lenght(arr)

9

In [176]:
arr = np.array(['orange juice', 'banana shake or juice', 'grape juice', 'pineapple juice'])
max_lenght(arr)

21

In [177]:
# 61 Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset 
# using NumPy's functions.
arr = np.random.randint(1,1001,100)

In [178]:
arr

array([386, 825, 996, 219,  95, 208, 861,  19, 700, 499, 284, 213, 806,
       416, 990, 740, 478, 587, 478, 985, 123,  76,  11, 493, 814, 880,
       553,  65, 839, 704, 663, 627, 755, 446, 232, 783, 440, 493, 430,
       871, 445, 324,  59, 637, 217, 899, 120, 848, 408, 934, 439, 433,
       458, 417, 766,   2, 460,  64, 946, 746, 355, 477, 749, 507, 195,
       516,  67,  61, 626, 159, 707, 943, 574, 503,   2, 793, 151,  54,
       250, 877, 202, 358, 610, 101,  13, 289, 497, 261, 313, 975, 225,
       110,  81, 426, 393, 473, 584, 365, 798, 656])

In [179]:
np.mean(arr)

470.01

In [180]:
np.median(arr)

459.0

In [181]:
np.var(arr)

83048.8699

In [182]:
np.std(arr)

288.18200828643

In [183]:
# 62 Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
arr = np.random.randint(1,100,50)

In [184]:
arr

array([79, 41, 87, 10, 41, 74, 36, 83, 31, 86, 63, 72,  2, 34, 22, 87, 12,
       78, 72, 45, 30, 15, 40,  3, 53, 63, 64, 17, 10, 81, 66, 84, 25, 85,
       86, 83, 15, 20, 32, 56, 93, 37, 37, 13, 49, 66, 86, 81, 77, 18])

In [185]:
np.percentile(arr,25)

26.25

In [186]:
np.percentile(arr,75)

78.75

In [187]:
# 63 Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.
arr1 = np.random.randint(1,50,10)
arr2 = np.random.randint(1,50,10)

In [188]:
arr1

array([22, 23,  7, 25,  5, 13,  7, 35, 43, 46])

In [189]:
arr2

array([22, 40, 10, 33, 48,  6, 13, 38,  8,  6])

In [190]:
correlation_matrix = np.corrcoef(arr1,arr2)

In [191]:
correlation_matrix

array([[ 1.        , -0.18762835],
       [-0.18762835,  1.        ]])

In [192]:
correlation_coefficient = correlation_matrix[0, 1] # [0,1] also gave same result >> means 2nd element of 1st row.
#correlation_coefficient = correlation_matrix[1, 0] # [1,0] also gave same result >> means 1st element of 2st row.

In [193]:
correlation_coefficient

-0.1876283501583102

In [194]:
# 64 Create two matrices and perform matrix multiplication using NumPy's `dot` function.
matrix1 = np.random.randint(1,8,(2,3))
matrix2 = np.random.randint(1,8,(3,2))

In [195]:
matrix1

array([[2, 4, 6],
       [5, 3, 1]])

In [196]:
matrix2

array([[6, 4],
       [7, 3],
       [1, 5]])

In [197]:
np.dot(matrix1,matrix2)

array([[46, 50],
       [52, 34]])

In [198]:
# 65 Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.
arr = np.random.randint(10,100,50)

In [199]:
arr

array([96, 27, 58, 74, 76, 84, 16, 90, 31, 15, 15, 17, 58, 57, 39, 16, 30,
       92, 66, 40, 75, 96, 43, 39, 51, 47, 95, 24, 11, 97, 54, 48, 27, 84,
       95, 16, 94, 21, 40, 80, 50, 33, 71, 89, 27, 42, 70, 11, 30, 84])

In [200]:
np.percentile(arr,10)

16.0

In [201]:
np.percentile(arr,50) #for 50th percentile you can also use np.median() give same result.

49.0

In [202]:
np.median(arr) 

49.0

In [203]:
np.percentile(arr,90)

94.1

In [204]:
np.percentile(arr,25) # 1st quartile

27.75

In [205]:
np.percentile(arr,75) # 3rd quartile

79.0

In [206]:
# 66 Create a NumPy array of integers and find the index of a specific element.
arr = np.random.randint(10,100,10)

In [207]:
arr

array([10, 21, 27, 69, 49, 46, 80, 68, 90, 64])

In [208]:
np.where(arr == 69) # indices of 69 is 5.

(array([3], dtype=int64),)

In [209]:
# 67 Generate a random NumPy array and sort it in ascending order.
arr = np.random.randint(5,50,10)

In [210]:
arr

array([20,  6, 28,  5, 11, 41, 39, 36, 38, 39])

In [211]:
np.sort(arr)

array([ 5,  6, 11, 20, 28, 36, 38, 39, 39, 41])

In [212]:
# 68 Filter elements >20  in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])

In [213]:
arr

array([12, 25,  6, 42,  8, 30])

In [214]:
arr[arr>20]

array([25, 42, 30])

In [215]:
# 69 Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])

In [216]:
arr

array([ 1,  5,  8, 12, 15])

In [217]:
arr[arr%3==0]

array([12, 15])

In [218]:
# 70 Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])

In [219]:
arr

array([10, 20, 30, 40, 50])

In [220]:
arr[(arr>=20) & (arr<=40)]

array([20, 30, 40])

In [221]:
# byteorder returns the byte order of the data type:
# '<' for little-endian
# '>' for big-endian
# '=' for native byte order (the byte order used by the system)
# '|' for the machine's native byte order (which is the same as =)
# For the default data types (like integers in most cases), NumPy uses the native byte order of the system unless explicitly specified otherwise. 
# Therefore, in many environments, the output would be '=', indicating native byte order.

# 71 For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])

In [222]:
byteord = arr.dtype.byteorder

In [223]:
print(byteord)

=


In [224]:
# 72 For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [225]:
arr

array([1, 2, 3])

In [226]:
arr.byteswap()

array([16777216, 33554432, 50331648])

In [227]:
# 73 For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [228]:
arr

array([1, 2, 3])

In [229]:
swap_arr = arr.newbyteorder()

In [230]:
swap_arr

array([16777216, 33554432, 50331648], dtype='>i4')

In [231]:
arr.dtype

dtype('int32')

In [232]:
swap_arr.dtype

dtype('>i4')

In [233]:
# 74 For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
import sys
arr = np.array([1, 2, 3], dtype=np.int32)
system_endianness = sys.byteorder
arrar_endianness = arr.dtype.byteorder
if arrar_endianness != system_endianness:
    print("byte swapping is neccesary for the array")
    swapped_array = arr.newbyteorder()
else:
    print("no need to change byte order if it's already correct")
    swapped_array = arr.copy() # no need to change byte order if it's already correct

byte swapping is neccesary for the array


In [234]:
arrar_endianness

'='

In [235]:
system_endianness

'little'

In [236]:
swapped_array

array([16777216, 33554432, 50331648], dtype='>i4')

In [237]:
# 75 For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
arr = np.array([1, 2, 3], dtype=np.int32)
system_endianness = sys.byteorder
arrar_endianness = arr.dtype.byteorder
if arrar_endianness == '=':
   print("the array is already in the sytem's native byte order") 
elif arrar_endianness == system_endianness:
    print("the array is already in the sytem's byte order")
else:
    print("byte swapping is neccesary for the array")
    swapped_array = arr.newbyteorder()

the array is already in the sytem's native byte order


In [238]:
system_endianness

'little'

In [239]:
arrar_endianness

'='

In [240]:
swapped_array

array([16777216, 33554432, 50331648], dtype='>i4')

In [241]:
# 76 Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`.
# Check if modifying `copy_arr` affects `arr1`.
arr1 = np.random.randint(1,11,5)
copy_arr1 = arr1.copy() # it's called deep copy if we change arr1 it not impact of copy_arr1.

In [242]:
arr1

array([3, 8, 4, 5, 1])

In [243]:
copy_arr1

array([3, 8, 4, 5, 1])

In [244]:
arr1[0]

3

In [245]:
arr1[0] = 2

In [246]:
arr1

array([2, 8, 4, 5, 1])

In [247]:
copy_arr1

array([3, 8, 4, 5, 1])

In [248]:
# 77 Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. 
# Modify an element in `view_slice` and observe if it changes the original `matrix`.
arr = np.random.randint(1,25,(3,3))
view_slice = arr[0:2,[0,2]] 

In [249]:
arr

array([[ 6,  5, 18],
       [18,  8, 21],
       [ 3, 13,  3]])

In [250]:
view_slice

array([[ 6, 18],
       [18, 21]])

In [251]:
view_slice[0][1]

18

In [252]:
view_slice[0][1] = 30 # it change the value in extract matrix but not in original matrix.

In [253]:
arr

array([[ 6,  5, 18],
       [18,  8, 21],
       [ 3, 13,  3]])

In [254]:
view_slice

array([[ 6, 30],
       [18, 21]])

In [255]:
# 78 Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. 
# Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.
array_a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
view_b = array_a[1:,[1,2]]

In [256]:
array_a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [257]:
view_b

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [258]:
view_b + 5 # change in view_b not impact the array_a in case of brodcasting

array([[10, 11],
       [13, 14],
       [16, 17]])

In [259]:
array_a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [260]:
# 79 Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) 
# from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.
orig_array = np.random.randint(1,9,(2,4)) 
reshaped_view = orig_array.reshape(4,2)

In [261]:
orig_array

array([[1, 5, 8, 8],
       [8, 6, 5, 1]])

In [262]:
reshaped_view

array([[1, 5],
       [8, 8],
       [8, 6],
       [5, 1]])

In [263]:
reshaped_view[2][1]

6

In [264]:
reshaped_view[2][1] = 4 # change in reshaped_view also impact in orig_array in case of reshape.

In [265]:
reshaped_view

array([[1, 5],
       [8, 8],
       [8, 4],
       [5, 1]])

In [266]:
orig_array

array([[1, 5, 8, 8],
       [8, 4, 5, 1]])

In [267]:
# 80 Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. 
# Modify an element in `data_copy` and verify if it affects the original `data`.
data = np.random.randint(1,15,(3,4))
data_copy = data[data>5]

In [268]:
data

array([[ 7, 12,  2,  5],
       [11,  9,  4, 14],
       [11,  6,  1,  1]])

In [269]:
data_copy

array([ 7, 12, 11,  9, 14, 11,  6])

In [270]:
data_copy[4] 

14

In [271]:
data_copy[4]  = 10 # change in data_copy not impact the data.

In [272]:
data_copy

array([ 7, 12, 11,  9, 10, 11,  6])

In [273]:
data

array([[ 7, 12,  2,  5],
       [11,  9,  4, 14],
       [11,  6,  1,  1]])

In [274]:
# 81 Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.
import numpy.matlib as nm
A = nm.random.randint(1,10,(3,3))
B = nm.random.randint(1,10,(3,3))

In [275]:
A

array([[6, 4, 1],
       [8, 4, 5],
       [7, 8, 6]])

In [276]:
B

array([[5, 7, 2],
       [1, 2, 5],
       [5, 3, 3]])

In [277]:
A+B

array([[11, 11,  3],
       [ 9,  6, 10],
       [12, 11,  9]])

In [278]:
A-B

array([[ 1, -3, -1],
       [ 7,  2,  0],
       [ 2,  5,  3]])

In [279]:
# 82 Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
A = nm.random.randint(1,10,(3,2))
B = nm.random.randint(1,10,(2,4))

In [280]:
A

array([[1, 5],
       [3, 2],
       [3, 1]])

In [281]:
B

array([[1, 4, 1, 2],
       [7, 3, 7, 4]])

In [282]:
A@B

array([[36, 19, 36, 22],
       [17, 18, 17, 14],
       [10, 15, 10, 10]])

In [283]:
# 83 Create a matrix `E` and find its transpose.
E = nm.random.randint(1,15,(2,5))

In [284]:
E

array([[10,  2,  8, 14, 12],
       [13, 11,  8,  6, 12]])

In [285]:
E.transpose()

array([[10, 13],
       [ 2, 11],
       [ 8,  8],
       [14,  6],
       [12, 12]])

In [286]:
# 84 Generate a square matrix `F` and compute its determinant.
F = np.random.randint(1,15,(4,4))
determinant_F = np.linalg.det(F)

In [287]:
F

array([[ 8,  1,  1,  4],
       [10, 10, 13,  1],
       [ 9,  3,  3,  6],
       [ 5, 14,  5,  3]])

In [288]:
int(determinant_F)

1943

In [289]:
# 85 Create a square matrix `G` and find its inverse.
G = np.random.randint(1,15,(4,4))
inverse_G = np.linalg.inv(G)

In [290]:
G

array([[ 9, 12,  7,  2],
       [ 7, 12,  5,  3],
       [12,  1,  3,  2],
       [ 7,  7,  7,  9]])

In [291]:
inverse_G

array([[-0.0676399 ,  0.07931873,  0.10851582, -0.03552311],
       [-0.09245742,  0.20194647, -0.0243309 , -0.04136253],
       [ 0.45352798, -0.49586375, -0.10170316,  0.08710462],
       [-0.22822384,  0.16690998,  0.0136253 ,  0.10316302]])